// AUTO-GENERATED by scripts/gen_report_types.py from analysis/lockedgroove/report.py.
// Do not edit by hand. analysis/tests/test_report_schema.py fails if this file is stale.

export const SCHEMA_VERSION = "3.0" as const;

export type FileKind = "original" | "stem" | "chop" | "loop_render" | "layer_render" | "revoice_render";
export type Mode = "major" | "minor";
export type Feel = "straight" | "swung" | "loose";
export type DrumSource = "sampled_break" | "programmed" | "mixed" | "unknown";
export type TagSource = "model" | "user";

export interface Beats {
  times_s: Array<number>;
  confidence: number;
  method: string;
  downbeats_s: Array<number>;
  downbeat_phase: number;
  downbeat_confidence: number;
  downbeat_method: string;
  meter: string;
  notes: string | null;
}

export interface ChordSegment {
  start_s: number;
  end_s: number;
  label: string;
  confidence: number;
}

export interface Chords {
  segments: Array<ChordSegment>;
  method: string;
  notes: string | null;
}

/**
 * One position of a per-section drum pattern on a 16th grid.
 *
 * ``step`` is 0..15 within the bar. ``frequency`` is the fraction of bars in
 * the section where a hit lands on this step. ``velocity`` is the mean
 * normalized hit strength. ``offset_ms`` is the mean measured offset from the
 * grid; positive is late. Offsets are what make the MIDI export keep the feel.
 */
export interface DrumHit {
  step: number;
  velocity: number;
  frequency: number;
  offset_ms: number;
}

export interface DrumPattern {
  section_index: number;
  kick: Array<DrumHit>;
  snare: Array<DrumHit>;
  hat: Array<DrumHit>;
  other: Array<DrumHit>;
  /** steps carrying accents */
  accents: Array<number>;
  density_per_bar: number;
  hat_open_ratio: number | null;
  /** snare steps with low velocity */
  ghost_notes: Array<number>;
}

export interface Drums {
  source_estimate: DrumSource;
  source_confidence: number;
  patterns: Array<DrumPattern>;
  layered_kick: boolean | null;
  method: string;
  notes: string | null;
}

export interface EffectsEstimates {
  reverb_tail_s: Estimate;
  sidechain_ducking: SidechainEstimate;
  saturation_above_hz: Estimate;
}

export interface Estimate {
  value: number | null;
  confidence: number;
  method: string;
  notes: string | null;
}

export interface FileInfo {
  id: string | null;
  sha256: string | null;
  original_filename: string | null;
  duration_s: number;
  sample_rate: number;
  channels: number;
  format: string | null;
  kind: FileKind;
  parent_file_id: string | null;
}

export interface Groove {
  swing_pct: number;
  timing_deviation_ms: TimingDeviation;
  feel: Feel;
  method: string;
  confidence: number;
}

export interface InstrumentEvent {
  instrument: string;
  bar: number;
}

export interface Instrumentation {
  per_section: Array<InstrumentationSection>;
  method: string;
  confidence: number;
}

export interface InstrumentationSection {
  section_index: number;
  present: Array<string>;
  entries: Array<InstrumentEvent>;
  exits: Array<InstrumentEvent>;
}

export interface Key {
  tonic: string;
  mode: Mode;
  confidence: number;
  method: string;
  alternate: KeyAlternate | null;
  notes: string | null;
}

export interface KeyAlternate {
  tonic: string;
  mode: "major" | "minor";
  correlation: number;
}

export interface KeyEdit {
  tonic: string;
  mode: "major" | "minor";
}

export interface Loudness {
  integrated_lufs: number;
  true_peak_dbtp: number;
  loudness_range_lu: number;
  method: string;
}

export interface Onsets {
  times_s: Array<number>;
  method: string;
  count: number;
}

/**
 * Present only while the report is still being written.
 *
 * A report is published stage by stage now (``pipeline.analyze_array``'s
 * ``on_partial``), so a producer sees a real tempo at twenty seconds instead
 * of a step name. That makes a new kind of mistake possible: something
 * downstream reading a half-written report as if it were everything we know,
 * and saying "no key was measured" about a stage that has not run yet.
 *
 * So a report under construction says so, in the report, and the rule is
 * exactly one line: **``pending`` is set while it is partial and ``None``
 * when it is finished.** Absence means complete, which keeps every reader
 * written before this field existed correct about a finished report; and a
 * partial is only ever stored while ``files.status = 'analyzing'``, so a
 * reader that never learns about this field still has the row's status to go
 * on. ``effective()`` carries it through untouched, and
 * ``web/lib/report/effective.ts`` mirrors both halves.
 *
 * ``done`` and ``stages`` are the report's own field names, so a reader can
 * say *which* measurement is still coming rather than only that one is.
 */
export interface Pending {
  /** report fields that have not run yet */
  stages: Array<string>;
  /** report fields that have run and are in this report */
  done: Array<string>;
  /** stages done / stages asked for */
  fraction: number;
}

export interface SampleUse {
  is_loop_based: boolean | null;
  chop_count_estimate: number | null;
  chop_reordering_detected: boolean | null;
  chop_order: Array<number>;
  pitch_shift_semitones_estimate: number | null;
  pitch_shift_source_file_id: string | null;
  /** bars where the sample is present */
  sample_bars: Array<number>;
  confidence: number;
  method: string;
  notes: string | null;
}

export interface Section {
  start_s: number;
  end_s: number;
  start_bar: number;
  bars: number;
  label: string;
  energy: number;
  confidence: number;
}

export interface SidechainEstimate {
  detected: boolean;
  depth_db: number | null;
  confidence: number;
  method: string;
}

export interface Spectral {
  centroid_hz_mean: number;
  stereo_width: number;
  low_high_ratio_db: number;
  method: string;
  bandwidth: Estimate | null;
}

export interface Structure {
  sections: Array<Section>;
  loop_period_bars: number | null;
  loop_period_confidence: number;
  method: string;
  notes: string | null;
}

export interface Tag {
  tag: string;
  confidence: number;
  source: TagSource;
}

export interface Tempo {
  bpm: number;
  confidence: number;
  method: string;
  /** [half, double] */
  alternates_bpm: Array<number>;
  notes: string | null;
}

export interface TimingDeviation {
  mean: number;
  std: number;
}

export interface UserEdits {
  tempo_bpm: number | null;
  downbeat_phase: number | null;
  first_downbeat_s: number | null;
  key: KeyEdit | null;
  meter: string | null;
  /** section index (as a string) -> label */
  section_labels: Record<string, string> | null;
  edited_at: string | null;
}

export interface AnalysisReport {
  schema_version: "3.0";
  analysis_version: number;
  file: FileInfo;
  tempo: Tempo | null;
  beats: Beats | null;
  key: Key | null;
  chords: Chords | null;
  onsets: Onsets | null;
  groove: Groove | null;
  structure: Structure | null;
  drums: Drums | null;
  sample_use: SampleUse | null;
  instrumentation: Instrumentation | null;
  loudness: Loudness | null;
  spectral: Spectral | null;
  effects_estimates: EffectsEstimates | null;
  tags: Array<Tag>;
  user_edits: UserEdits;
  /** set while the analysis is still running; None on a finished report (see Pending) */
  pending: Pending | null;
}

export const REPORT_SECTIONS = [
  "tempo",
  "beats",
  "key",
  "chords",
  "onsets",
  "groove",
  "structure",
  "drums",
  "sample_use",
  "instrumentation",
  "loudness",
  "spectral",
  "effects_estimates",
] as const;
export type ReportSection = (typeof REPORT_SECTIONS)[number];
