// AUTO-GENERATED by scripts/gen_stem_models.py from
// analysis/lockedgroove/stems/separate.py. Do not edit by hand.
//
// Separation is the irreversible step: a weak separator throws away high
// frequencies that no EQ downstream puts back. So the registry is ordered by
// quality and the product asks for a *split* — the stems it wants — rather
// than for a model by name. The worker resolves the best separator installed
// in its image that makes those stems, and the `stems` row it writes carries
// the tier, the published SDR and a sentence about it.

export type SeparationTier = "reference" | "strong" | "baseline" | "weak" | "stand_in";

export type StemModelId = "bs_roformer" | "mdx23c_inst_voc" | "htdemucs_ft" | "htdemucs_6s" | "mdxnet_inst_hq" | "kuielab_other";

export interface StemModelSpec {
  id: StemModelId;
  /** the stems it returns */
  stems: readonly string[];
  /** what it is, in words a producer can read */
  label: string;
  family: string;
  tier: SeparationTier;
  /** published SDR, or null when its author published none */
  sdr: number | null;
  /** what that number is and where it came from — never show `sdr` without it */
  sdrBasis: string;
}

export interface StemSplit {
  /** the stems this split returns */
  stems: readonly string[];
  /** the best tier any model reaches for this split */
  bestTier: SeparationTier;
  /** what would run if every checkpoint were installed; the row says what did */
  bestModel: StemModelId;
  /** every model that makes this split, best first */
  models: readonly StemModelId[];
  isDefault: boolean;
}

/** Tiers, best first. */
export const TIERS: readonly SeparationTier[] = ["reference", "strong", "baseline", "weak", "stand_in"];

/** How far a claim made from a stem of this tier should be trusted. */
export const TIER_CONFIDENCE: Record<SeparationTier, number> = {
  reference: 0.9,
  strong: 0.75,
  baseline: 0.55,
  weak: 0.35,
  stand_in: 0.1,
};

/** One sentence about the tier, for the producer rather than for us. */
export const TIER_NOTE: Record<SeparationTier, string> = {
  reference: "highest-quality separator available; the source's top end survives it",
  strong: "strong separator; the best full-split option",
  baseline: "older separator; audibly softer than the reference tier",
  weak: "low-quality separator: it loses high-frequency detail that cannot be recovered downstream",
  stand_in: "development stand-in, not a separation model; nothing measured from it is a real stem",
};

/** Every model, best first — the order the worker walks when it resolves. */
export const STEM_MODELS: readonly StemModelSpec[] = [
  {
    id: "bs_roformer",
    stems: ["vocals", "instrumental"],
    label: "Band-split transformer (vocals / instrumental)",
    family: "bs-roformer",
    tier: "reference",
    sdr: 12.98,
    sdrBasis: "vocals SDR published by the checkpoint's author",
  },
  {
    id: "mdx23c_inst_voc",
    stems: ["vocals", "instrumental"],
    label: "MDX23C 8k FFT (vocals / instrumental)",
    family: "mdx23c",
    tier: "reference",
    sdr: 11.0,
    sdrBasis: "vocals SDR published by the checkpoint's author",
  },
  {
    id: "htdemucs_ft",
    stems: ["drums", "bass", "vocals", "other"],
    label: "Hybrid transformer, fine-tuned (drums, bass, vocals, other)",
    family: "demucs",
    tier: "strong",
    sdr: 9.0,
    sdrBasis: "four-stem average SDR on the standard separation benchmark, published by the author",
  },
  {
    id: "htdemucs_6s",
    stems: ["drums", "bass", "vocals", "other", "guitar", "piano"],
    label: "Hybrid transformer, six-stem (adds guitar and piano)",
    family: "demucs",
    tier: "strong",
    sdr: null,
    sdrBasis: "no per-stem SDR published for the six-stem variant",
  },
  {
    id: "mdxnet_inst_hq",
    stems: ["vocals", "instrumental"],
    label: "Spectrogram U-net, instrumental (vocals / instrumental)",
    family: "mdx-net",
    tier: "baseline",
    sdr: null,
    sdrBasis: "no SDR published on a standard benchmark",
  },
  {
    id: "kuielab_other",
    stems: ["other"],
    label: "Spectrogram U-net, melodic residue only",
    family: "kuielab",
    tier: "weak",
    sdr: null,
    sdrBasis: "no SDR published on a standard benchmark",
  },
];

/** The splits a producer may ask for. `weak` and `stand_in` models make none. */
export const STEM_SPLITS: readonly StemSplit[] = [
  {
    stems: ["drums", "bass", "vocals", "other"],
    bestTier: "strong",
    bestModel: "htdemucs_ft",
    models: ["htdemucs_ft", "htdemucs_6s"],
    isDefault: true,
  },
  {
    stems: ["vocals", "instrumental"],
    bestTier: "reference",
    bestModel: "bs_roformer",
    models: ["bs_roformer", "mdx23c_inst_voc", "mdxnet_inst_hq"],
    isDefault: false,
  },
  {
    stems: ["drums", "bass", "vocals", "other", "guitar", "piano"],
    bestTier: "strong",
    bestModel: "htdemucs_6s",
    models: ["htdemucs_6s"],
    isDefault: false,
  },
];

/** What a request with no split asks for. */
export const DEFAULT_STEMS: readonly string[] = ["drums", "bass", "vocals", "other"];

/** Every stem name any model returns. Display order lives in lib/api/stems.ts. */
export const ALL_STEMS: readonly string[] = ["vocals", "instrumental", "drums", "bass", "other", "guitar", "piano"];
