#!/usr/bin/env python3
"""Generate the web app's separator catalogue from the Python registry.

  web/lib/types/stemModels.ts   the models, their tiers, and the splits they make

Run after any change to ``MODELS`` in analysis/lockedgroove/stems/separate.py:

    python scripts/gen_stem_models.py

analysis/tests/test_stem_models_gen.py fails if the committed file is stale, and
CI runs this script with ``--check``.

Why generate it at all: separation is the irreversible step, and the registry is
ordered by quality so the best separator that makes the asked-for stems is the
one that runs. The web had its own copy of that registry, typed by hand, three
entries deep out of six, defaulting to a model by name. So the ordering never
reached the producer: they were asked to choose between identifiers they cannot
evaluate, and the tier the backend already knew was never shown. One registry,
generated, is the only way that stays true.
"""

from __future__ import annotations

import argparse
import json
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "analysis"))

from lockedgroove.stems.separate import (  # noqa: E402
    DEFAULT_STEMS,
    MODELS,
    TIER_CONFIDENCE,
    TIER_NOTE,
    TIER_RANK,
    TIERS,
    _sort_key,
    best_model,
    models_for,
)

TS_PATH = ROOT / "web" / "lib" / "types" / "stemModels.ts"

#: A split is only offered when a model that is not ``weak`` or ``stand_in``
#: produces it. Those two tiers exist so a row that came from one can be
#: *labelled*; nothing should be able to ask for one by choosing a split.
OFFERABLE_TIERS = ("reference", "strong", "baseline")


def _q(s: str) -> str:
    return json.dumps(s)


def _union(values) -> str:
    return " | ".join(_q(v) for v in values)


def ranked_models() -> list[str]:
    """Every model, best first — the order `resolve_model` walks."""
    return sorted(MODELS, key=_sort_key)


def splits() -> list[dict]:
    """The distinct stem sets a producer may ask for, best tier first.

    One entry per *output set* of an offerable model, deduplicated, carrying the
    best model that makes it. That model is what would run if every checkpoint
    were installed; the worker resolves against the image it is actually in, and
    the `stems` row it writes says which one ran.
    """
    seen: dict[tuple[str, ...], dict] = {}
    for model in ranked_models():
        spec = MODELS[model]
        if spec["tier"] not in OFFERABLE_TIERS:
            continue
        key = tuple(spec["stems"])
        if key in seen:
            continue
        chosen = best_model(key) or model
        seen[key] = {
            "stems": list(key),
            "bestModel": chosen,
            "bestTier": MODELS[chosen]["tier"],
            "isDefault": set(key) == set(DEFAULT_STEMS),
            "models": models_for(key),
        }
    order = sorted(
        seen.values(),
        key=lambda s: (not s["isDefault"], TIER_RANK[s["bestTier"]], -len(s["stems"]), s["stems"]),
    )
    return order


def all_stems() -> list[str]:
    """Every stem name any model returns, first-seen order across the ranked models."""
    out: list[str] = []
    for model in ranked_models():
        for stem in MODELS[model]["stems"]:
            if stem not in out:
                out.append(stem)
    return out


def render_ts() -> str:
    lines: list[str] = [
        "// AUTO-GENERATED by scripts/gen_stem_models.py from",
        "// analysis/lockedgroove/stems/separate.py. Do not edit by hand.",
        "//",
        "// Separation is the irreversible step: a weak separator throws away high",
        "// frequencies that no EQ downstream puts back. So the registry is ordered by",
        "// quality and the product asks for a *split* — the stems it wants — rather",
        "// than for a model by name. The worker resolves the best separator installed",
        "// in its image that makes those stems, and the `stems` row it writes carries",
        "// the tier, the published SDR and a sentence about it.",
        "",
        f"export type SeparationTier = {_union(TIERS)};",
        "",
        f"export type StemModelId = {_union(ranked_models())};",
        "",
        "export interface StemModelSpec {",
        "  id: StemModelId;",
        "  /** the stems it returns */",
        "  stems: readonly string[];",
        "  /** what it is, in words a producer can read */",
        "  label: string;",
        "  family: string;",
        "  tier: SeparationTier;",
        "  /** published SDR, or null when its author published none */",
        "  sdr: number | null;",
        "  /** what that number is and where it came from — never show `sdr` without it */",
        "  sdrBasis: string;",
        "}",
        "",
        "export interface StemSplit {",
        "  /** the stems this split returns */",
        "  stems: readonly string[];",
        "  /** the best tier any model reaches for this split */",
        "  bestTier: SeparationTier;",
        "  /** what would run if every checkpoint were installed; the row says what did */",
        "  bestModel: StemModelId;",
        "  /** every model that makes this split, best first */",
        "  models: readonly StemModelId[];",
        "  isDefault: boolean;",
        "}",
        "",
        "/** Tiers, best first. */",
        f"export const TIERS: readonly SeparationTier[] = [{', '.join(_q(t) for t in TIERS)}];",
        "",
        "/** How far a claim made from a stem of this tier should be trusted. */",
        "export const TIER_CONFIDENCE: Record<SeparationTier, number> = {",
    ]
    for tier in TIERS:
        lines.append(f"  {tier}: {TIER_CONFIDENCE[tier]},")
    lines += [
        "};",
        "",
        "/** One sentence about the tier, for the producer rather than for us. */",
        "export const TIER_NOTE: Record<SeparationTier, string> = {",
    ]
    for tier in TIERS:
        lines.append(f"  {tier}: {_q(TIER_NOTE[tier])},")
    lines += [
        "};",
        "",
        "/** Every model, best first — the order the worker walks when it resolves. */",
        "export const STEM_MODELS: readonly StemModelSpec[] = [",
    ]
    for model in ranked_models():
        spec = MODELS[model]
        sdr = "null" if spec["sdr"] is None else repr(float(spec["sdr"]))
        lines += [
            "  {",
            f"    id: {_q(model)},",
            f"    stems: [{', '.join(_q(s) for s in spec['stems'])}],",
            f"    label: {_q(spec['label'])},",
            f"    family: {_q(spec['family'])},",
            f"    tier: {_q(spec['tier'])},",
            f"    sdr: {sdr},",
            f"    sdrBasis: {_q(spec['sdr_basis'])},",
            "  },",
        ]
    lines += [
        "];",
        "",
        "/** The splits a producer may ask for. `weak` and `stand_in` models make none. */",
        "export const STEM_SPLITS: readonly StemSplit[] = [",
    ]
    for split in splits():
        lines += [
            "  {",
            f"    stems: [{', '.join(_q(s) for s in split['stems'])}],",
            f"    bestTier: {_q(split['bestTier'])},",
            f"    bestModel: {_q(split['bestModel'])},",
            f"    models: [{', '.join(_q(m) for m in split['models'])}],",
            f"    isDefault: {'true' if split['isDefault'] else 'false'},",
            "  },",
        ]
    lines += [
        "];",
        "",
        "/** What a request with no split asks for. */",
        f"export const DEFAULT_STEMS: readonly string[] = [{', '.join(_q(s) for s in DEFAULT_STEMS)}];",
        "",
        "/** Every stem name any model returns. Display order lives in lib/api/stems.ts. */",
        f"export const ALL_STEMS: readonly string[] = [{', '.join(_q(s) for s in all_stems())}];",
        "",
    ]
    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true", help="fail if the committed file is stale")
    args = ap.parse_args()

    rendered = render_ts()
    if args.check:
        current = TS_PATH.read_text() if TS_PATH.exists() else ""
        if current != rendered:
            print(f"{TS_PATH.relative_to(ROOT)} is stale; run scripts/gen_stem_models.py", file=sys.stderr)
            return 1
        print(f"{TS_PATH.relative_to(ROOT)} is up to date")
        return 0

    TS_PATH.parent.mkdir(parents=True, exist_ok=True)
    TS_PATH.write_text(rendered)
    print(f"wrote {TS_PATH.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
