#!/usr/bin/env python3
"""Generate the two derived forms of the AnalysisReport from the Pydantic models.

  docs/analysis_report.schema.json   JSON Schema (draft 2020-12)
  web/lib/types/report.ts            TypeScript types for the web app

Run after any change to analysis/lockedgroove/report.py:

    python scripts/gen_report_types.py

analysis/tests/test_report_schema.py fails if the committed files are stale.
"""

from __future__ import annotations

import json
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "analysis"))

from lockedgroove.report import json_schema  # noqa: E402

SCHEMA_PATH = ROOT / "docs" / "analysis_report.schema.json"
TS_PATH = ROOT / "web" / "lib" / "types" / "report.ts"

# Literal unions that get a named alias in TypeScript: (interface, field) -> alias
NAMED_UNIONS = {
    ("FileInfo", "kind"): "FileKind",
    ("Key", "mode"): "Mode",
    ("Groove", "feel"): "Feel",
    ("Drums", "source_estimate"): "DrumSource",
    ("Tag", "source"): "TagSource",
}


def _ts_type(prop: dict, owner: str, field: str) -> str:
    alias = NAMED_UNIONS.get((owner, field))
    if alias and "enum" in prop:
        return alias
    if "$ref" in prop:
        return prop["$ref"].split("/")[-1]
    if "anyOf" in prop:
        parts = [_ts_type(p, owner, field) for p in prop["anyOf"]]
        return " | ".join(dict.fromkeys(parts))
    if "enum" in prop:
        return " | ".join(json.dumps(v) for v in prop["enum"])
    if "const" in prop:
        return json.dumps(prop["const"])
    t = prop.get("type")
    if t == "string":
        return "string"
    if t in ("number", "integer"):
        return "number"
    if t == "boolean":
        return "boolean"
    if t == "null":
        return "null"
    if t == "array":
        return f"Array<{_ts_type(prop.get('items', {}), owner, field)}>"
    if t == "object":
        ap = prop.get("additionalProperties")
        if isinstance(ap, dict):
            return f"Record<string, {_ts_type(ap, owner, field)}>"
        if "properties" in prop:
            inner = "; ".join(f"{k}: {_ts_type(v, owner, k)}" for k, v in prop["properties"].items())
            return "{ " + inner + " }"
        return "Record<string, unknown>"
    return "unknown"


def _interface(name: str, schema: dict) -> str:
    lines: list[str] = []
    desc = schema.get("description")
    if desc:
        lines.append("/**")
        for line in desc.strip().splitlines():
            lines.append(f" * {line}".rstrip())
        lines.append(" */")
    lines.append(f"export interface {name} {{")
    for field, prop in schema.get("properties", {}).items():
        fdesc = prop.get("description")
        if fdesc:
            lines.append(f"  /** {fdesc} */")
        lines.append(f"  {field}: {_ts_type(prop, name, field)};")
    lines.append("}")
    return "\n".join(lines)


def render_ts(schema: dict) -> str:
    out: list[str] = [
        "// AUTO-GENERATED by scripts/gen_report_types.py from analysis/lockedgroove/report.py.",
        "// Do not edit by hand. analysis/tests/test_report_schema.py fails if this file is stale.",
        "",
        f'export const SCHEMA_VERSION = "{schema["properties"]["schema_version"]["const"]}" as const;',
        "",
    ]
    defs = schema.get("$defs", {})
    # named unions first
    for (owner, field), alias in NAMED_UNIONS.items():
        prop = defs[owner]["properties"][field]
        enum = prop.get("enum")
        if enum is None and "anyOf" in prop:
            for p in prop["anyOf"]:
                if "enum" in p:
                    enum = p["enum"]
        if enum is None and "$ref" in prop:
            enum = defs[prop["$ref"].split("/")[-1]].get("enum")
        assert enum, f"no enum for {owner}.{field}"
        out.append(f"export type {alias} = {' | '.join(json.dumps(v) for v in enum)};")
    out.append("")
    for name, sub in defs.items():
        if "properties" not in sub:
            continue  # bare enums are inlined
        out.append(_interface(name, sub))
        out.append("")
    out.append(_interface(schema["title"], schema))
    out.append("")
    # The measured sections, which is what "what did this record come back
    # knowing" means. `pending` is bookkeeping about the analysis rather than a
    # measurement, so it is left out for the same reason `file` and
    # `user_edits` are: `notAnalyzed()` would otherwise report it as a section
    # the record has no reading for.
    out.append("export const REPORT_SECTIONS = [")
    for field, prop in schema["properties"].items():
        if field in ("schema_version", "analysis_version", "file", "tags", "user_edits", "pending"):
            continue
        out.append(f'  "{field}",')
    out.append("] as const;")
    out.append("export type ReportSection = (typeof REPORT_SECTIONS)[number];")
    out.append("")
    return "\n".join(out)


def render_schema(schema: dict) -> str:
    return json.dumps(schema, indent=2) + "\n"


def main(check: bool = False) -> int:
    schema = json_schema()
    want_schema = render_schema(schema)
    want_ts = render_ts(schema)
    if check:
        ok = True
        if not SCHEMA_PATH.exists() or SCHEMA_PATH.read_text() != want_schema:
            print(f"stale: {SCHEMA_PATH}")
            ok = False
        if not TS_PATH.exists() or TS_PATH.read_text() != want_ts:
            print(f"stale: {TS_PATH}")
            ok = False
        return 0 if ok else 1
    SCHEMA_PATH.parent.mkdir(parents=True, exist_ok=True)
    TS_PATH.parent.mkdir(parents=True, exist_ok=True)
    SCHEMA_PATH.write_text(want_schema)
    TS_PATH.write_text(want_ts)
    print(f"wrote {SCHEMA_PATH.relative_to(ROOT)} and {TS_PATH.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main(check="--check" in sys.argv))
