"""Loop renderer: zero-crossing snap, tail/self crossfade, WAV export, and the shared vector.

BUILD_PACKET section 7; OPEN_QUESTIONS D.19-20. ``fixtures/loop_render_vector.json``
is generated by ``scripts/gen_loop_vector.py`` from this implementation and
asserted by ``web/lib/audio/renderLoop.test.ts`` as well.
"""

import json
import pathlib

import numpy as np
import pytest
import soundfile as sf

from lockedgroove.loops.render import (
    DEFAULT_CROSSFADE_MS,
    ZERO_CROSSING_MAX_MS,
    equal_power_curve,
    export_wav,
    mono_sum,
    render_loop,
    round_half_up,
    snap_to_zero_crossing,
)

FIXTURES = pathlib.Path(__file__).parent / "fixtures"
SR = 44100
HZ = 110.0
AMP = 0.6


def stereo_tone(seconds: float = 2.0, sr: int = SR) -> np.ndarray:
    t = np.arange(int(round(seconds * sr))) / sr
    left = AMP * np.sin(2 * np.pi * HZ * t)
    right = 0.8 * AMP * np.sin(2 * np.pi * HZ * t + 0.5)
    return np.stack([left, right]).astype(np.float32)


def natural_max_step() -> float:
    """Largest sample-to-sample step the tone itself has."""
    return AMP * 2 * np.pi * HZ / SR


def wrap_jump(out: np.ndarray) -> float:
    return float(np.max(np.abs(out[:, 0].astype(np.float64) - out[:, -1].astype(np.float64))))


def max_step(out: np.ndarray) -> float:
    return float(np.max(np.abs(np.diff(out.astype(np.float64), axis=1))))


# --- tail crossfade -------------------------------------------------------------------------------


def test_tail_crossfade_removes_the_seam_click():
    y = stereo_tone()
    start_s, end_s = 0.1, 0.5023  # 44.25 cycles: the raw cut lands a quarter cycle off phase
    raw = y[:, round_half_up(start_s * SR):round_half_up(end_s * SR)]
    assert wrap_jump(raw) > 0.3, "the raw cut is supposed to click"
    out, meta = render_loop(y, SR, start_s, end_s)
    assert meta["mode"] == "tail"
    assert meta["crossfade_samples"] == round_half_up(DEFAULT_CROSSFADE_MS * SR / 1000)
    assert out.shape == (2, meta["end_sample"] - meta["start_sample"])
    assert out.dtype == np.float32
    assert wrap_jump(out) < 0.05
    # nothing inside the loop, the crossfade included, moves faster than the tone itself (with margin)
    assert max_step(out) < 3 * natural_max_step()
    looped = np.concatenate([out, out], axis=1)
    assert max_step(looped) < 3 * natural_max_step()
    # the first crossfade sample is the natural continuation of the last one
    e = meta["end_sample"]
    assert np.allclose(out[:, 0], y[:, e], atol=1e-6)
    # past the crossfade the loop is the untouched audio
    cf = meta["crossfade_samples"]
    assert np.array_equal(out[:, cf:], y[:, meta["start_sample"] + cf:e])


def test_crossfade_is_head_times_fade_in_plus_post_end_times_fade_out():
    y = stereo_tone()
    out, meta = render_loop(y, SR, 0.25, 0.75, crossfade_ms=10.0, snap_zero_crossing=False)
    s, e, cf = meta["start_sample"], meta["end_sample"], meta["crossfade_samples"]
    fade_in, fade_out = equal_power_curve(cf)
    expect = (y[:, s:s + cf].astype(np.float64) * fade_in + y[:, e:e + cf].astype(np.float64) * fade_out)
    assert np.allclose(out[:, :cf], expect.astype(np.float32), atol=1e-7)


def test_crossfade_zero_is_a_raw_cut_and_cap_is_half_the_loop():
    y = stereo_tone()
    out, meta = render_loop(y, SR, 0.1, 0.5, crossfade_ms=0.0)
    assert meta["crossfade_samples"] == 0
    assert np.array_equal(out, y[:, meta["start_sample"]:meta["end_sample"]])
    out2, meta2 = render_loop(y, SR, 0.1, 0.1 + 20 / 1000, crossfade_ms=12.0, snap_zero_crossing=False)
    assert meta2["crossfade_samples"] == out2.shape[1] // 2


# --- zero-crossing snap ---------------------------------------------------------------------------


def test_snap_lands_on_a_zero_crossing_and_never_moves_more_than_2ms():
    y = stereo_tone()
    out, meta = render_loop(y, SR, 0.1, 0.5015)  # end is 1.5 ms past a crossing of the 110 Hz tone
    assert -2.0 <= meta["snapped_end_ms"] < -1.0
    assert abs(meta["snapped_start_ms"]) <= 2.0
    m = mono_sum(y)
    for edge in (meta["start_sample"], meta["end_sample"]):
        a, b = m[edge - 1], m[edge]
        assert (a <= 0 <= b) or (b <= 0 <= a)
    assert meta["start_s"] == meta["start_sample"] / SR and meta["end_s"] == meta["end_sample"] / SR
    assert out.shape[1] == meta["end_sample"] - meta["start_sample"]


def test_snap_bound_holds_for_arbitrary_indices_and_rates():
    rng = np.random.default_rng(0)
    for sr in (8000, 22050, 44100, 48000, 96000):
        n = sr // 4
        y = np.stack([rng.standard_normal(n), rng.standard_normal(n)]).astype(np.float32) * 0.3
        for idx in rng.integers(0, n + 1, size=200):
            j = snap_to_zero_crossing(y, sr, int(idx), ZERO_CROSSING_MAX_MS)
            assert 0 <= j <= n
            assert abs(j - int(idx)) * 1000.0 / sr <= ZERO_CROSSING_MAX_MS
        assert snap_to_zero_crossing(y, sr, 0) == 0 and snap_to_zero_crossing(y, sr, n) == n


def test_snap_keeps_the_edge_when_no_crossing_is_in_range():
    n = SR
    y = (0.5 + 0.01 * np.sin(2 * np.pi * 50 * np.arange(n) / SR)).astype(np.float32)  # never crosses zero
    for idx in (1000, 12345, n - 1000):
        assert snap_to_zero_crossing(y, SR, idx) == idx
    # the file boundaries count as crossings, so an edge within 2 ms of them snaps onto them
    assert snap_to_zero_crossing(y, SR, n - 10) == n
    assert snap_to_zero_crossing(y, SR, 10) == 0
    assert snap_to_zero_crossing(y, SR, 100) == 100  # 2.3 ms in: out of range of the boundary
    out, meta = render_loop(np.stack([y, y]), SR, 0.1, 0.6)
    assert meta["snapped_start_ms"] == 0.0 and meta["snapped_end_ms"] == 0.0
    assert meta["start_sample"] == round_half_up(0.1 * SR) and meta["end_sample"] == round_half_up(0.6 * SR)


def test_snap_uses_the_mono_sum_so_channels_move_together():
    n = 4000
    sr = 8000
    left = np.zeros(n, dtype=np.float32) + 0.2
    right = np.zeros(n, dtype=np.float32) - 0.2
    left[2000:] = -0.2  # left crosses at 2000; right never does; the sum is zero everywhere
    y = np.stack([left, right])
    assert snap_to_zero_crossing(y, sr, 1995) == 1995  # the sum is zero at every index, so no move
    right[:] = -0.1  # now the sum crosses only at 2000
    assert snap_to_zero_crossing(np.stack([left, right]), sr, 1995) == 2000
    assert snap_to_zero_crossing(np.stack([left, right]), sr, 1990) == 2000  # 10 samples = 1.25 ms, in range
    assert snap_to_zero_crossing(np.stack([left, right]), sr, 1984) == 2000  # 16 samples = 2.0 ms, still in range
    assert snap_to_zero_crossing(np.stack([left, right]), sr, 1983) == 1983  # 17 samples: out of range, stays


def test_snap_disabled_keeps_exact_edges():
    y = stereo_tone()
    out, meta = render_loop(y, SR, 0.1, 0.5015, snap_zero_crossing=False)
    assert meta["start_sample"] == round_half_up(0.1 * SR)
    assert meta["end_sample"] == round_half_up(0.5015 * SR)
    assert meta["snapped_start_ms"] == 0.0 and meta["snapped_end_ms"] == 0.0


# --- self-crossfade fallback and shapes -----------------------------------------------------------


def test_self_crossfade_fallback_triggers_at_end_of_file():
    y = stereo_tone(seconds=2.0)
    out, meta = render_loop(y, SR, 0.1, 1.995)  # fewer than 12 ms remain after the end
    assert meta["mode"] == "self"
    assert meta["crossfade_samples"] == round_half_up(DEFAULT_CROSSFADE_MS * SR / 1000)
    s, e, cf = meta["start_sample"], meta["end_sample"], meta["crossfade_samples"]
    assert out.shape == (2, e - s)
    # the head is untouched; the blend sits at the tail and lands on the head's own lead-in
    assert np.array_equal(out[:, :cf], y[:, s:s + cf])
    assert not np.array_equal(out[:, -cf:], y[:, e - cf:e])
    assert np.allclose(out[:, -1], y[:, s - 1], atol=1e-6)
    assert wrap_jump(out) < 0.05
    assert max_step(np.concatenate([out, out], axis=1)) < 3 * natural_max_step()


def test_whole_file_loop_is_a_raw_cut():
    y = stereo_tone(seconds=1.0)
    out, meta = render_loop(y, SR, 0.0, 1.0)
    assert meta["mode"] == "self" and meta["crossfade_samples"] == 0
    assert (meta["start_sample"], meta["end_sample"]) == (0, y.shape[1])
    assert np.array_equal(out, y)


def test_channel_count_is_preserved_and_mono_comes_back_as_1xn():
    y = stereo_tone()
    out, meta = render_loop(y[0], SR, 0.1, 0.5)
    assert out.ndim == 2 and out.shape[0] == 1 and meta["channels"] == 1
    assert out.shape[1] == meta["end_sample"] - meta["start_sample"] == meta["length_samples"]
    out3, meta3 = render_loop(np.stack([y[0], y[1], y[0]]), SR, 0.1, 0.5)
    assert out3.shape[0] == 3 and meta3["channels"] == 3
    # (n, channels) layout is accepted too
    out_t, _ = render_loop(y.T, SR, 0.1, 0.5)
    assert np.array_equal(out_t, render_loop(y, SR, 0.1, 0.5)[0])


def test_meta_shape():
    y = stereo_tone()
    _, meta = render_loop(y, SR, 0.1, 0.5, crossfade_ms=8.0)
    assert set(meta) >= {"start_s", "end_s", "start_sample", "end_sample", "crossfade_ms", "crossfade_samples",
                         "mode", "snapped_start_ms", "snapped_end_ms"}
    assert meta["crossfade_ms"] == 8.0 and meta["sample_rate"] == SR
    json.dumps(meta)


def test_invalid_ranges_raise():
    y = stereo_tone()
    with pytest.raises(ValueError):
        render_loop(y, SR, 0.5, 0.5)
    with pytest.raises(ValueError):
        render_loop(y, SR, 0.6, 0.5)
    with pytest.raises(ValueError):
        render_loop(np.zeros((2, 0), dtype=np.float32), SR, 0.0, 0.1)
    with pytest.raises(ValueError):
        render_loop(y, 0, 0.0, 0.1)


# --- curve ----------------------------------------------------------------------------------------


def test_equal_power_curve():
    fi, fo = equal_power_curve(529)
    assert fi[0] == 0.0 and fo[0] == 1.0
    assert fi[-1] == pytest.approx(1.0) and fo[-1] == pytest.approx(0.0, abs=1e-12)
    assert np.allclose(fi ** 2 + fo ** 2, 1.0, atol=1e-12)
    assert np.all(np.diff(fi) > 0) and np.all(np.diff(fo) < 0)
    fi1, fo1 = equal_power_curve(1)
    assert fi1[0] == pytest.approx(np.sqrt(0.5)) and fo1[0] == pytest.approx(np.sqrt(0.5))
    fi0, fo0 = equal_power_curve(0)
    assert fi0.size == 0 and fo0.size == 0


# --- export ---------------------------------------------------------------------------------------


@pytest.mark.parametrize("bit_depth,subtype,atol", [(24, "PCM_24", 2e-7), (16, "PCM_16", 4e-5)])
def test_export_wav_roundtrip(tmp_path, bit_depth, subtype, atol):
    y = stereo_tone()
    out, meta = render_loop(y, SR, 0.1, 0.7)
    path = tmp_path / "loop.wav"
    assert export_wav(path, out, SR, bit_depth=bit_depth) == str(path)
    info = sf.info(str(path))
    assert info.subtype == subtype and info.format == "WAV"
    assert info.channels == 2 and info.samplerate == SR and info.frames == out.shape[1]
    back, back_sr = sf.read(str(path), dtype="float32", always_2d=True)
    assert back_sr == SR
    assert np.allclose(back.T, out, atol=atol)


def test_export_wav_mono_and_bad_depth(tmp_path):
    y = stereo_tone()
    out, _ = render_loop(y[0], SR, 0.1, 0.3)
    path = tmp_path / "mono.wav"
    export_wav(path, out, SR)
    assert sf.info(str(path)).channels == 1
    with pytest.raises(ValueError):
        export_wav(tmp_path / "x.wav", out, SR, bit_depth=32)


# --- shared vector --------------------------------------------------------------------------------


@pytest.fixture(scope="module")
def vector():
    return json.loads((FIXTURES / "loop_render_vector.json").read_text())


def _check_case(vec: dict, case: dict, channel_indices: list[int]) -> None:
    y = np.asarray([vec["channels"][i] for i in channel_indices], dtype=np.float32)
    if len(channel_indices) == 1:
        y = y[0]
    out, meta = render_loop(y, vec["sample_rate"], case["start_s"], case["end_s"],
                            crossfade_ms=case["crossfade_ms"], snap_zero_crossing=case["snap_zero_crossing"])
    exp = case["expected"]
    assert meta["start_sample"] == exp["start_sample"] and meta["end_sample"] == exp["end_sample"]
    assert meta["start_s"] == exp["start_s"] and meta["end_s"] == exp["end_s"]
    assert meta["mode"] == exp["mode"] and meta["crossfade_samples"] == exp["crossfade_samples"]
    assert meta["snapped_start_ms"] == exp["snapped_start_ms"] and meta["snapped_end_ms"] == exp["snapped_end_ms"]
    assert out.shape == (exp["channels"], exp["length"])
    idx = np.asarray(exp["indices"])
    for c in range(exp["channels"]):
        got = out[c, idx].astype(np.float64)
        want = np.asarray(exp["values"][c], dtype=np.float64)
        assert np.max(np.abs(got - want)) < vec["tolerance"]


def test_shared_vector_primary_case(vector):
    assert vector["sample_rate"] == 8000 and len(vector["channels"]) == 2
    assert len(vector["expected"]["indices"]) >= 250
    assert vector["expected"]["mode"] == "tail"
    _check_case(vector, vector, [0, 1])


def test_shared_vector_extra_cases(vector):
    names = {c["name"] for c in vector["extra_cases"]}
    assert {"self_mode_end_of_file", "no_snap", "mono_short_crossfade", "whole_file_raw"} <= names
    for case in vector["extra_cases"]:
        _check_case(vector, case, case["channel_indices"])
    modes = {c["name"]: c["expected"]["mode"] for c in vector["extra_cases"]}
    assert modes["self_mode_end_of_file"] == "self"


def test_shared_vector_is_current():
    import subprocess
    import sys

    script = pathlib.Path(__file__).resolve().parents[2] / "scripts" / "gen_loop_vector.py"
    res = subprocess.run([sys.executable, str(script), "--check"], capture_output=True, text=True)
    assert res.returncode == 0, res.stdout + res.stderr
    assert (FIXTURES / "loop_render_vector.json").stat().st_size < 200 * 1024
