// Turning a measured bandwidth into something a producer can act on.
//
// `bandwidthFixture.json` is generated by
// analysis/tests/test_quality_bandwidth.py from real measurements of real
// signals — a wideband file, the 15.7 kHz and 12.0 kHz lowpasses that match the
// uploads in the first sessions, a downsampled working copy, and silence. The
// thresholds here are therefore checked against what the measurement actually
// returns rather than against numbers typed on this side.

import { describe, expect, it } from "vitest";
import fixture from "./bandwidthFixture.json";
import { limitsTheFlip, sourceFidelity } from "./bandwidth";
import type { Estimate as ReportEstimate } from "@/lib/types/report";

const est = (c: keyof typeof fixture): ReportEstimate => fixture[c] as ReportEstimate;

describe("sourceFidelity", () => {
  it("calls a wideband file full, and holds nothing against it", () => {
    const f = sourceFidelity(est("full_band"))!;
    expect(f.grade).toBe("full");
    expect(limitsTheFlip(f)).toBe(false);
    expect(f.verdict).toContain("full top end");
  });

  it("calls the 15.7 kHz upload limited, because that one sounded muffled", () => {
    // 12.0, 13.5 and 15.7 kHz were the real uploads, and every layer built from
    // them was dull. 15.7 belongs on the wrong side of the line.
    const f = sourceFidelity(est("lossy_15k7"))!;
    expect(f.hz).toBeLessThan(16_500);
    expect(f.grade).toBe("limited");
    expect(limitsTheFlip(f)).toBe(true);
  });

  it("calls the 12 kHz upload limited and says a cleaner source is the fix", () => {
    const f = sourceFidelity(est("limited_12k"))!;
    expect(f.grade).toBe("limited");
    expect(f.verdict).toContain("cleaner source");
    expect(f.khz).toBe("12.1");
  });

  // The case the generated fixture caught: a working copy reports the copy's
  // own ceiling, and grading it would tell a producer their source is the
  // problem when the file may be perfect.
  it("refuses to grade a measurement taken on a downsampled working copy", () => {
    const f = sourceFidelity(est("working_copy"))!;
    expect(f.confidence).toBeLessThan(0.4);
    expect(f.grade).toBe("unclear");
    expect(limitsTheFlip(f)).toBe(false);
    expect(f.verdict).toContain("nothing is being claimed");
    expect(f.note).toContain("re-measure on the upload");
  });

  it("says nothing at all when nothing was measured", () => {
    expect(sourceFidelity(est("silence"))).toBeNull();
    expect(sourceFidelity(null)).toBeNull();
    expect(sourceFidelity(undefined)).toBeNull();
  });

  it("does not invent a grade from a nonsense value", () => {
    const bad = (value: number): ReportEstimate => ({ value, confidence: 0.9, method: "m", notes: null });
    expect(sourceFidelity(bad(0))).toBeNull();
    expect(sourceFidelity(bad(-1))).toBeNull();
    expect(sourceFidelity(bad(Number.NaN))).toBeNull();
  });

  it("carries the measurement's own caveat through in its own words", () => {
    // The `nyquist_limited` flag never reaches the report, so re-deriving this
    // on the web would mean sniffing Python's prose. It is read out instead.
    expect(sourceFidelity(est("full_band"))!.note).toContain("the sample rate is the limit, not the record");
  });
});
