// Reading what the finder measured about a loop's span.
//
// The blocks are not written here. `sampleReadyFixture.json` is generated by
// analysis/tests/test_loops_sample_ready.py from the same fixture audio and the
// same code path that writes them in production, and that test fails when the
// committed file no longer matches. A fixture typed out on this side would be
// the web's *idea* of the shape, and an idea drifts — which is how the
// separator catalogue ended up three models deep out of six.
//
// What is tested here is the reading: that a withheld claim never reads as
// false, that a loop with no block reads as "not measured" rather than as
// "nothing playing", and that junk cannot produce a confident-looking chip.

import { describe, expect, it } from "vitest";
import { claimIsTrue, sampleReadyChips, sampleReadyOf } from "./sampleReady";
import fixture from "./sampleReadyFixture.json";

const measured = { sample_ready: fixture.vocal_free_span, seam: 0.82 };
const vocalOver = { sample_ready: fixture.vocal_over_it_span };
const withheld = { sample_ready: fixture.weak_separation };
const standIn = { sample_ready: fixture.stand_in };

describe("sampleReadyOf", () => {
  it("reads the claims, the chips and the separation behind them", () => {
    const ready = sampleReadyOf(measured)!;
    expect(ready.source.tier).toBe("strong");
    expect(ready.source.confidence).toBe(0.75);
    expect(ready.claims.vocal_free?.value).toBe(true);
    expect(ready.reasons[0]).toMatch(/no vocal/);
    expect(ready.caveats.length).toBeGreaterThan(0);
  });

  it("is null for a loop that was never measured, which is not the same as empty", () => {
    expect(sampleReadyOf({ seam: 0.82 })).toBeNull();
    expect(sampleReadyOf(null)).toBeNull();
    expect(sampleReadyOf([1, 2, 3])).toBeNull();
    expect(sampleReadyOf("sample_ready")).toBeNull();
  });

  it("keeps a withheld claim null rather than letting it read as false", () => {
    const ready = sampleReadyOf(withheld)!;
    expect(ready.source.trusted).toBe(false);
    expect(ready.claims.vocal_free?.value).toBeNull();
    expect(ready.claims.vocal_free?.withheld).toContain("weak-tier");
    expect(claimIsTrue(ready, "vocal_free")).toBe(false);
  });

  it("reads the vocal-over span as measured-and-false, which is not withheld", () => {
    const ready = sampleReadyOf(vocalOver)!;
    expect(ready.claims.vocal_free?.value).toBe(false);
    expect(ready.claims.vocal_free?.withheld).toBeUndefined();
    expect(claimIsTrue(ready, "vocal_free")).toBe(false);
  });

  it("never reports a claim as true just because something is there", () => {
    const junk = { sample_ready: { claims: { vocal_free: { value: "yes" } }, reasons: "no vocal" } };
    const ready = sampleReadyOf(junk)!;
    expect(ready.claims.vocal_free?.value).toBeNull();
    expect(ready.reasons).toEqual([]);
    expect(claimIsTrue(ready, "vocal_free")).toBe(false);
  });

  it("takes an old block at its word when it predates the tier", () => {
    // Reading a missing `trusted` as untrusted would silence chips that were
    // correct when they were written.
    const old = { sample_ready: { source: { model: "htdemucs_ft" }, claims: {}, reasons: ["drums only: this is the break"] } };
    const ready = sampleReadyOf(old)!;
    expect(ready.source.trusted).toBe(true);
    expect(ready.source.tier).toBeNull();
    expect(sampleReadyChips(ready)).toEqual(["drums only: this is the break"]);
  });
});

describe("sampleReadyChips", () => {
  it("shows what Python worded, not a re-derivation of it", () => {
    expect(sampleReadyChips(sampleReadyOf(measured))).toEqual(fixture.vocal_free_span.reasons);
    expect(sampleReadyChips(sampleReadyOf(vocalOver))).toEqual(fixture.vocal_over_it_span.reasons);
  });

  it("says we did not look, rather than showing nothing, when the separation is not claim-grade", () => {
    const chips = sampleReadyChips(sampleReadyOf(withheld));
    expect(chips).toEqual(["stems came from a weak-tier separator: no claim about this span"]);
    // and a real separator is never described to a producer as a stand-in
    expect(chips[0]).not.toContain("stand-in");
    expect(sampleReadyChips(sampleReadyOf(standIn))[0]).toContain("stand-in");
  });

  it("shows nothing at all for a loop that was never measured", () => {
    expect(sampleReadyChips(null)).toEqual([]);
    expect(sampleReadyChips(sampleReadyOf({ seam: 0.5 }))).toEqual([]);
  });

  it("shows nothing when a trusted separation simply had nothing to say", () => {
    const quiet = { sample_ready: { source: { trusted: true }, claims: {}, reasons: [] } };
    expect(sampleReadyChips(sampleReadyOf(quiet))).toEqual([]);
  });
});
